repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: "#1"
          name: format
          entry: pdm run format
          language: system
          always_run: true
          pass_filenames: false
        - id: "#2"
          name: code standards, docstring, and imports check
          entry: pdm run check
          language: system
          always_run: true
          pass_filenames: false
        - id: "#3"
          name: dead code check
          entry: pdm run check-dead
          language: system
          always_run: true
          pass_filenames: false
        - id: "#4"
          name: type check
          entry: pdm run check-typing
          language: system
          always_run: true
          pass_filenames: false
        - id: "#5"
          name: test
          entry: pdm run test
          language: system
          always_run: true
          pass_filenames: false