repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.5.0
      hooks:
        - id: check-added-large-files
    - repo: local
      hooks:
        - id: flake8
          name: flake8
          entry: pdm run flake8
          language: system
          always_run: true
          pass_filenames: false
        - id: pyupgrade
          name: pyupgrade
          entry: pdm run pyupgrade
          language: system
          always_run: true
          pass_filenames: false
        - id: black
          name: black
          entry: pdm run black
          language: system
          always_run: true
          pass_filenames: false
        - id: refurb
          name: refurb
          entry: pdm run refurb
          language: system
          always_run: true
          pass_filenames: false
        - id: isort
          name: isort
          entry: pdm run isort
          language: system
          always_run: true
          pass_filenames: false
        - id: mypy
          name: mypy
          entry: pdm run mypy
          language: system
          always_run: true
          pass_filenames: false
        - id: pydocstyle
          name: pydocstyle
          entry: pdm run pydocstyle
          language: system
          always_run: true
          pass_filenames: false
        - id: test
          name: test
          entry: pdm run pytest --cov=missil tests/
          language: system
          always_run: true
          pass_filenames: false